<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\GlutenFree.Databricks.AdoNet.Linq2Db\GlutenFree.Databricks.AdoNet.Linq2Db.csproj" />
    <ProjectReference Include="..\GlutenFree.Databricks.AdoNet.IntegrationTests\GlutenFree.Databricks.AdoNet.IntegrationTests.csproj" />
  </ItemGroup>

</Project>
