<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\GlutenFree.Databricks.AdoNet\GlutenFree.Databricks.AdoNet.csproj" />
    <ProjectReference Include="..\GlutenFree.Databricks.AdoNet.Tests\GlutenFree.Databricks.AdoNet.Tests.csproj" />
  </ItemGroup>

</Project>
