<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GlutenFree.Databricks.AdoNet.Thrift\GlutenFree.Databricks.AdoNet.Thrift.csproj" />
    <ProjectReference Include="..\GlutenFree.Databricks.AdoNet.IntegrationTests\GlutenFree.Databricks.AdoNet.IntegrationTests.csproj" />
    <ProjectReference Include="..\GlutenFree.Databricks.AdoNet.Linq2Db.IntegrationTests\GlutenFree.Databricks.AdoNet.Linq2Db.IntegrationTests.csproj" />
  </ItemGroup>

</Project>
