<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>GlutenFree.Databricks.AdoNet</PackageId>
    <Description>Open source ADO.NET data provider for Databricks SQL warehouses.</Description>
    <PackageTags>databricks;ado.net;sql;data;provider</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GlutenFree.Databricks.AdoNet.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Apache.Arrow" Version="23.0.0" />
    <PackageReference Include="Apache.Arrow.Compression" Version="23.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

</Project>
